name: CatchmentForcings
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pygeoogc=0.11.0
  - pygeoutils=0.11.0
  - py3dep=0.11.0
  - pynhd=0.11.0
  - pygeohydro=0.11.0
  - pydaymet=0.11.0
  - geemap
  - wxee
  - eemont
  - rioxarray
  - openpyxl
  - cdsapi
  - cfgrib
  - tqdm
  - sphinx
  - pytest
  - black
  - flake8
  - pip
  - pip:
      - wget
      - hydrodataset
      - hydroutils
